### ISSUE TITLE
使用vue3和element-plus报错如下。

### ISSUE THREAD

**Issue by dxsjk** [molian-Z/OmniMagicCube#3]
X [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

    node_modules/omni-magic-cube/index.es.js:1:7:
      1 │ import require$$0, { onMounted, nextTick, watch, unref, isRef, getCurrentInstance, ref, readonly, getCurrentScope, onScopeDispose, toRefs as toRefs$1, customRef, comp... 
        ╵        ~~~~~~~~~~

C:\Users\26644\WebstormProjects\cube1\node_modules\esbuild\lib\main.js:1651
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
node_modules/omni-magic-cube/index.es.js:1:7: ERROR: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
    at failureErrorWithLog (C:\Users\26644\WebstormProjects\cube1\node_modules\esbuild\lib\main.js:1651:15)
    at C:\Users\26644\WebstormProjects\cube1\node_modules\esbuild\lib\main.js:1059:25
    at C:\Users\26644\WebstormProjects\cube1\node_modules\esbuild\lib\main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

package.json文件如下
{
  "name": "cube1",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "element-plus": "^2.7.0",
    "omni-magic-cube": "^0.12.8",
    "vue": "^3.4.21"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "vite": "^5.2.0"
  }
}

**Comment by molian-Z** [comment]
快走

**Comment by dxsjk** [comment]
> 快走

ok

**Comment by molian-Z** [comment]
可以引用umd路径来使用 es打包有点问题我这几天看看修复一下
